import Head from 'next/head';

import {
  Box,
  Text,
  Stack,
  Link,
  useColorMode,
  Center,
} from '@chakra-ui/react';
import {  MintNfts } from '../components';
import WelcomeMsg from 'components/home/welcome';
import WhosInvolvedMsg from 'components/home/whos-involved';
import Steps from 'components/home/steps';
import RegisterMsg from 'components/home/register-modal';


export default function Home() {


  return (
    <div className='site-background'>
      <Head>
        <title>Locality</title>
        <meta name="description" content="Generated by create cosmos app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Box className="main-page" textAlign="center">
        <Box pos="relative" overflow="hidden">
          <WelcomeMsg />
          <Steps />
          <br />
          <MintNfts />
          <WhosInvolvedMsg />
          <RegisterMsg/>
        </Box>
      </Box>

      <Stack
        isInline={true}
        spacing={1}
        justifyContent="center"
        opacity={0.5}
        fontSize="sm"
      >
        <Text>Built Permissionlessly with</Text>
        <Link
          href="https://cosmology.tech/"
          target="_blank"
          rel="noopener noreferrer"
        >
          Cosmology
        </Link>
      </Stack>

    </div>
  );
}
